### PR TITLE
125 Bug - Video thumbnail for Key Facts with video component is not correctly displayed on Safari

### LINKED ISSUE #125: Bug - Major - Safari browser - Key Facts - Video thumbnail for Key Facts with video component is not correctly displayed on Safari
Video thumbnail from a Key Facts with video component is not correctly displayed on Safari browser

**Steps to reproduce:**
1. Open https://42-key-facts--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/key-facts on Safari browser and scroll down to Key Facts with Video component
2. Notice that the video thumbnail is not correctly displayed

**Expected result**
Video thumbnail should be correctly displayed

**Actual result**
Video thumbnail is not correctly displayed on Safari browser
image

### PR DESCRIPTION
**Pull request by cogniSyb**
Fix #125

Test URLs:
- Before: https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
- After: https://125-safari-key-facts-video--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

### CODE REVIEW

File: tools/importer/import.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ const linkToHlxPage = (main, document, url) => {
     if (new RegExp('^(https?:)?//').test(link.href)) {
       // leave links with domains as is
     } else if (link.href.startsWith('/')) {
-      const newUrl = new URL(link.href, 'https://main--vg-volvotrucks-us--hlxsites.hlx.page');
+      const newUrl = new URL(link.href, 'https://main--vg-volvotrucks-us-rd--netcentric.hlx.page');
```
Comment (TomaszDziezykNetcentric) [inline tools/importer/import.js:77]: @cogniSyb 
@manuel-vara 
Do we have some steps before prod to change it back to the `https://main--vg-volvotrucks-us--hlxsites.hlx.page`?

**Review by TomaszDziezykNetcentric — APPROVED** [review]

**Review by markovukiceviccn — APPROVED** [review]
