### PR TITLE
fix in page navigation

### LINKED ISSUE #95: Bug - Major - iPhone - In-Page Navigation - Selecting a section from the subnavigation menu will not update the Subnavigation header
When opening In-Page Navigation in Mobile view and selecting a section from the menu - the Subnavigation header will not be updated to the currently selected section, only the first default section will be displayed there

**Expected result**
01. Open https://45-in-page-navigation--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/inpage-navigation in Mobile View
02. Open the Subnavigation menu and select a section, Section 2 for example
03. Notice that the first default section is still displayed in the Subnavigation header "Section 4 (1)" although Section 2 has been selected and it is in view

**Expected result**
The selected tab from the Subnavigation menu should be displayed in the header

**Actual result**
The Subnavigation header will not be updated to the currently selected section, only the first default section will be displayed there

### PR DESCRIPTION
**Pull request by kesiah**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #95

Test URLs:
- Before: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
- After: https://95-bug-inpagenavigation--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

### CODE REVIEW

File: blocks/v2-inpage-navigation/v2-inpage-navigation.js [hunk 1]
```diff
@@ -42,6 +42,29 @@ const inpageNavigationButton = () => {
   return null;
 };
 
+// Retrieve an array of sections with its corresponding intersectionRatio
+const wrapSectionItens = (elements) => {
```
Comment (markovukiceviccn) [inline blocks/v2-inpage-navigation/v2-inpage-navigation.js:46]: Typo "Itens"

Comment (kesiah) [reply blocks/v2-inpage-navigation/v2-inpage-navigation.js]: changed 😅

**Review by Lakshmishri — APPROVED** [review]

**Review by cogniSyb — APPROVED** [review]
